name: Code Quality Checks
on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]
jobs:
  all:
    name: All Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: 1.66.0
          override: true
          profile: minimal
          components: clippy, rustfmt
      - name: Set Up Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
      - name: Run All Checks
        run: |
          echo Test
          cargo test || touch fail
          echo Check
          cargo check || touch fail
          echo Clippy
          cargo clippy -- -D warnings || touch fail
          echo Format
          cargo fmt --all -- --check || touch fail
          test ! -e fail
